name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python 07-practicing-urls-and-views/manage.py test
    - name: Run Django server with Gunicorn
      run: |
        python 07-practicing-urls-and-views/manage.py migrate
        nohup gunicorn wsgi:application --chdir 07-practicing-urls-and-views --bind 127.0.0.1:8000 &
        sleep 5
        curl --fail http://127.0.0.1:8000/challenges || (echo "Server failed to respond" && exit 1)

